Add "arrivalCircle" to "nextPoint"
SignalK/specification pull request #628
Opened 2021-10-23 06:24 UTC by panaaj

Addition of `arrivalCircle` to `nextPoint` to allow an arrival alarm to be implemented.

2021-10-31 15:21 UTC, tkurki requested changes
I think it would be useful to add this to https://github.com/SignalK/specification/blob/master/test/data/full-valid/course-full_tree.json#L48

Oh I just noticed that the hrefs in that doc put resources under a vessel...

2021-10-31 23:37 UTC, panaaj commented
Added tests for `nextPoint.arrivalCircle`.
I have noticed two things in the test data that don't align with the text in the proposed CourseAPI.
1. `href` test value is under vessels _("href": "/vessels/vessels.urn:mrn:imo:mmsi:230099999/resources/waypoints/...")_
 when in practice `resources` is at the root of `./signalk/v1/api`.
2. `arrivalCircleEntered` notification is defined as `notifications.arrivalCircleEntered` where the proposed notification path in the Course API PR is `notifications.navigation.course.arrivalCircleEntered` 

Should these be updated in the test file?

2021-11-03 18:53 UTC, tkurki commented
I'll merge this, submit a new PR for fixes?

2021-11-03 18:57 UTC, tkurki commented
Oh, please rebase. Would do it myself nicely if the branch were under this repo ;-)

2026-06-19 01:29 UTC, closed without merging